### ISSUE TITLE
Open Thread: Ideas for IFTTT Triggers

### ISSUE THREAD

**Issue by gbinal** [18F/ifgovthenthat#2]
Share your ideas for triggers, preferably with a link to the api or data that would be behind it.

**Comment by gbinal** [comment]
When a new farmers market is added near you.

**Comment by konklone** [comment]
Your tax return has been accepted. (IRS)

**Comment by konklone** [comment]
The federal government has closed down or is delayed. (OPM)

**Comment by konklone** [comment]
An Amber Alert has been issued. (?)

**Comment by jpyuda** [comment]
severe weather alerts (flash flood, hurricane, tornado, etc)

**Comment by webmaven** [comment]
A new dataset has been released (matching some criteria, such as agency).

**Comment by webmaven** [comment]
Muckrock has released a new FOIA response that matches some criteria (such as agency).

**Comment by webmaven** [comment]
A new WeThePeople petition has been created that matches some criteria.

**Comment by webmaven** [comment]
A Federal IT project has crossed some threshold of cost or time overrun, so send me a message.

API: https://www.itdashboard.gov/data_feeds

**Comment by webmaven** [comment]
Notify me when works enter the public domain. _crickets_

**Comment by webmaven** [comment]
Notify me when new additions are made to https://public.resource.org/

**Comment by webmaven** [comment]
Notify me when my IRS refund has been sent.

**Comment by webmaven** [comment]
Notify me when desegregation orders for my jurisdiction/district are lifted. See: http://www.propublica.org/article/lack-of-order-the-erosion-of-a-once-great-force-for-integration

**Comment by webmaven** [comment]
Notify me when there is a toxic release in my community.

**Comment by webmaven** [comment]
Notify me when a food item I have purchased has been recalled.

**Comment by webmaven** [comment]
Notify me when a bridge I commute over has not had it's scheduled inspection.

**Comment by webmaven** [comment]
Notify me when a security vulnerability or other flaw has been found for a medical device I have implanted in me.

**Comment by webmaven** [comment]
When Bureau of Labor Statistics releases new projections on occupations, send me a notification that analyzes the impact on _my_ profession in particular (including my age, stage of career, and location) along with advice on training, retraining, etc. available that would best take advantage of or ameliorate that impact as warranted. 

Also, digest the data and republish it in a form useful to school career counselors.

**Comment by gbinal** [comment]
- Every time a petition reaches the threshold for responses in We The People 
- Every time a petition reaches the threshold for being public in We The People

**Comment by gbinal** [comment]
Every time a new data set is added to data.gov

**Comment by leahbannon** [comment]
Cleaning up README file and moving previous ideas collection here:
- if census releases economic indicator above/below something
- government status changes (opm.gov/status)
- USAJobs, FOIA, Federal Register keywords come up
- CPSC recalls - Jed Sundwall
- New entries on regulations.gov - @alandelevie
- TSA security line wait times reach a certain time
- I would say 'farmers market opens for the year' but think that the metadata for that API isn't parsed out well enough for that.  - @gbinal
- I wonder if it'd be possible to use the NREL API to power something that would alert you whenever there's a new alternative fuel station that opens within a certain geographic area... - @gbinal
- Maybe airport status (not quite the same as line times)?  E.G.  Triggers that are based off of an airport getting shut down.  I feel like many frequent flyers would be interested in getting a heads up of an event like this morning's at LAX for any airport in the lower 48, not just certain ones.  - @gbinal
- A we the people petition passes x number of signatures, includes x keywords
- "I had always envisioned agencies pushing each of their posts from any platform into an open Google Calendar so they can better see the spread of coverage between their sub-agencies, etc, and there would also be an easy to evaluate record for the public." - Justin Herman
- Do a "cook-off"/hackathon w/ fed devs and IFTTT folks - @erie
- If Natural Disaster (per NOAA) then Resources (localized per GPS) (FEMA) + (CDC) + (HHS) + (Coast Guard) + (National Guard) @hobokenmartha
- Link to Google Docs / Dropbox so that APIs with information can be downloaded easily and tracked by people who may have uses for them that we can't think of. - @mkramer
- Connect all projects to Google Drive or Dropbox for people to collect information for future projects that we might not be aware of yet. (i.e. information about clinical trials, etc.) - @mkramer
- If natural disaster happens, publish data from National Map: http://catalog.data.gov/dataset/the-national-map - @mkramer
- If a certain person or organization visits the White House (use White House visitor log API) notify me by email/tweet it/etc. - @mkramer
- If it's my birthday, send me a random newspaper from my birthday that's been digitized by the Library of Congress: http://chroniclingamerica.loc.gov/about/api/ -@mkramer
- If the government creates a new social media account (http://registery.usa.gov) follow them/tweet about it/etc.

**Comment by rebeccawilliams** [comment]
Hi all, I went to create an [OPM alert for myself](https://ifttt.com/recipes/253400-alert-my-iphone-whenever-there-is-an-opm-2-hr-delay) yesterday and found [many IFTTT recipes](https://ifttt.com/recipes/search?q=opm&ac=false) have already been created with their handy RSS feed. (@konklone) 

Same thing goes for the [NOAA Severe Weather alert feed](https://ifttt.com/recipes/search?q=noaa&ac=false). (@jpyuda) 

This makes me think the following: 
- I wish these were promoted more; it'd be great to see a If Gov Then That Collection: https://ifttt.com/recipes/collections or some other round up. 
- I think a lot of the ideas above could be created **today** with the RSS feeds that are available and there's no need to create a custom IFTTT API/Trigger.

**Comment by gbinal** [comment]
@rebeccawilliams - I'm not sure how readily we get on the official IFTTT collections page but agree with you entirely.  

Let's start by gathering [federal IFTTT recipes in this repo](https://github.com/18F/ifgovthenthat#ifgovthenthat-collection).  I've started it off with the two you mention.

**Comment by leahbannon** [comment]
@stvnrlly didn't you run into problems with OPM's RSS feed the last time we had a snow delay?

**Comment by stvnrlly** [comment]
Yeah, I did, but it may have been a one-time thing. For some reason, the RSS feed didn't update until that evening, by which point it was no longer useful. It was my first time paying attention to it, and every time since then has seemed to work properly.

**Comment by monfresh** [comment]
Not sure if y'all are aware, but OPM has a mobile app that can send you push notifications, and you can choose what type of alerts you want to receive. It's available for all major mobile platforms: http://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/mobile-app/

**Comment by rebeccawilliams** [comment]
@monfresh Yup, I have that installed as well. :smile:

**Comment by rebeccawilliams** [comment]
Here are some Fed RSS roundups to help suss out what's already possible and where a custom IFTTT API would add the most value: 
- [USA.gov's U.S. Government RSS Directory](http://www.usa.gov/Topics/Reference-Shelf/Libraries/RSS-Library.shtml)
- & [on Data.gov](http://catalog.data.gov/dataset?q=rss+OR++res_format%3Arss+OR+res_format%3Aapplication%2Frss%2Bxml)

Re: 'Every time a new dataset is added to Data.gov', here's the Data.gov CKAN API for [today](http://catalog.data.gov/api/3/action/package_search?q=metadata_created:[2015-02-02T00:00:00.000Z%20TO%20*]) and for [2015 so far](http://catalog.data.gov/api/3/action/package_search?q=metadata_created:[2015-01-01T00:00:00.000Z%20TO%20*]) -- it's a lot of alerts! I am exploring if we can get something going in Yahoo Pipes (a la [Chicago](https://twitter.com/opendatachicago)), but we welcome any future IFTTT channels.

**Comment by melodykramer** [comment]
Send me an alert when a FEMA disaster is declared within X number of miles: http://catalog.data.gov/dataset/fema-disaster-declarations-summary

**Comment by melodykramer** [comment]
Notify me of the place where it rained the most in the US yesterday: http://catalog.data.gov/dataset/u-s-hourly-precipitation-data

**Comment by melodykramer** [comment]
https://ifttt.com/space <-- These are good and could be applicable to lots of things.

**Comment by konklone** [comment]
In addition to triggers, can anyone think of gov platforms that can _receive_ events? The only ones I can think of (White House Petitions, Regulations.gov) both really require longform writing and it's tough to think of how they might be appropriate places for automated submissions from other services.

**Comment by stvnrlly** [comment]
USPS could have a useful event-receiving API, particularly the shipping label and package pickup ones: https://www.usps.com/business/web-tools-apis/list-of-apis.htm.

**Comment by melodykramer** [comment]
Good ideas in here: http://www.civomega.com/

**Comment by ghost** [comment]
Google has aggregated a variety of public alerts 

http://stackoverflow.com/questions/860442/google-alerts-api

https://support.google.com/publicalerts/?hl=en#2366580

http://google.org/publicalerts

**Comment by xocliwtb** [comment]
USPTO patent filed, issued, expiring

**Comment by jcfrench** [comment]
Um, you guys are awesome, but based on the general ideas you are submitting, you are missing a fundamental aspect of how the government serves citizens. You are thinking of citizens as individuals, which is true... rarely. Usually, the concerns of citizens are merged into organizations. One of the main concerns of those organizations are government grant processes. The true killer trigger is when a government agency puts either a grant, request for proposal, or request for bid out on the street. Every agency has a slightly different way of doing these things... but IFTTT...

When Grant applications open... let interested and appropriate non-profits, local governments, and commercial entities know through new communication mediums. When a grant moves forward, has a hiccup, etc, IFTTT, let the potential Grantees know sooner.

Grants, Certification, Easements, Penalties, Industrial Policy changes, Contract Awards, etc. All of these organizations have legacy ways of interacting... Can we add APIs for the next generation of these organizations? How long will my Business Development Staff have to scrounge through dated government websites which are only sluggishly updated?

IFTTT... follow the expenditures of each agency, where is the money going? Is this agency Granting, Servicing, Regulating, etc... IFTTT depends on who they interact with directly. That's usually not an individual citizen. Could you reverse this effort for a second by determining where each agency is sinking it's money, and IFTTT on the ways money is supporting organized groups of citizens? (Put some data analysis on this first to inform your challenge space, and then brain storm) That might change your thinking and hone you into more relevant ideas, instead of nice ideas for a gal or guy with a smartphone walking across campus.

**Comment by konklone** [comment]
@jcfrench Your point's well taken, but bear in mind that we're talking here specifically about IFTTT channels/triggers, and not about what APIs are worth building around government services.

> Grants, Certification, Easements, Penalties, Industrial Policy changes, Contract Awards, etc. All of these organizations have legacy ways of interacting... Can we add APIs for the next generation of these organizations? How long will my Business Development Staff have to scrounge through dated government websites which are only sluggishly updated?

Couldn't agree more -- 18F's [first project](https://fbopen.gsa.gov/) is an API aimed squarely at businesses looking for contract opportunities. There's more work like this happening in the 18F, Presidential Innovation Fellow, and US Digital Service family.

Here we're just talking about making use of existing data and APIs to build IFTTT integrations. IFTTT is primarily a consumer platform. Organizations and businesses are, by and large, probably going to have the incentive and resources to talk to APIs directly, or use other more professionally oriented tools that sit atop those APIs to get work done, rather than an IFTTT channel.

But if we're missing something here, and there are some existing APIs in government whose IFTTT integration would benefit a business like yours, please do link us to them and suggest some ideas here.

**Comment by deardooley** [comment]
- Office/school/organization openings, closings, business hours, change in contact info.
- Hiring opportunities (ie. new job postings, office vacancies, new positions created, etc)
- Hiring decisions
- Election vote casting (perhaps via web socket, but likely via batch updates)
- Congressional vote casting (by official, region, bill, etc)
- New or updated laws 
- Daily changes in health code statuses.
- Permit grants/expirations/revocations
- Licensing grants/expirations/revocations
- Campaign contributions (aggregated deltas by time period, candidate/official, region, time in office, party)
- FEMA declarations
- Patent filings/acceptance/rejection
- Equipment auctions/sales
- Visa filings/decisions
- Citizenship decisions
- Election results
- Flight status
- Environmental warnings (water supply, contaminations, spills, etc)

**Comment by ocapweb-usgs** [comment]
Create an IFTTT trigger to tap into the Social Media Registry (and allowing for the various API options...tags, agencies, etc). https://github.com/usagov/Social-Media-Registry-API-Documentation
